### ISSUE TITLE
[minor] create_entity  autocomplete extra text

### ISSUE THREAD

**Issue by Nexela** [Yokmp/atom-autocomplete-factorio#4]
create_entity  (and possibly some others) when autocompled put extra stuff on the line

`create_entity{name=…,position=…,direction=…,force=…,target=…,source=…,fast_replace=…,player=…,spill=…}→`

would it be possible to have it remove the arrow and the end and possibly the elipses

Thanks

**Comment by Yokmp** [comment]
Should be fixed now. 
Sidenote:
When you use [CTRL]+[ARROW_KEY] to navigate in Atom, you'll notice that the behavior seems a bit inconsistent at first.
If you press the left Arrow-Key it sets the Cursor right before the comma/equal sign.
By pressing the right one it sets the Cursor right after these two.
I could get around this by using Snippets instead of Suggestions ... hmm
